# Generated by Django 5.2.6 on 2026-09-10 00:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRewardRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('trigger', models.CharField(choices=[('signup', 'Referred student signs up'), ('paid', "Referred student's access fee is confirmed"), ('offer', 'Referred student receives an offer'), ('enrolled', 'Referred student enrols')], db_index=True, max_length=12)),
                ('calculation', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', "Percentage of the referred student's payment")], default='fixed', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Naira for a fixed reward; percent (e.g. 10.00) for a percentage reward.', max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage rewards.', max_digits=10, null=True)),
                ('owner_type', models.CharField(blank=True, choices=[('student', 'Student'), ('partner', 'External partner / influencer'), ('staff', 'Agency staff')], help_text='Blank applies the rule to every owner type.', max_length=10)),
                ('min_referrals', models.PositiveIntegerField(default=0, help_text='Tier gate: only applies from this many prior conversions onward.')),
                ('max_referrals', models.PositiveIntegerField(blank=True, help_text='Tier ceiling, exclusive.', null=True)),
                ('requires_manual_approval', models.BooleanField(default=False, help_text='Hold the reward for review instead of auto-approving.')),
                ('auto_approve_below', models.DecimalField(blank=True, decimal_places=2, help_text='Rewards at or above this amount always wait for a human (§6.2).', max_digits=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher wins when several rules match.')),
            ],
            options={
                'ordering': ('-priority', 'trigger'),
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('owner_type', models.CharField(choices=[('student', 'Student'), ('partner', 'External partner / influencer'), ('staff', 'Agency staff')], default='student', max_length=10)),
                ('partner_name', models.CharField(blank=True, max_length=150)),
                ('partner_email', models.EmailField(blank=True, max_length=254)),
                ('partner_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Blank means unlimited.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('signup', 'Signed up'), ('paid', 'Access fee paid'), ('offer', 'Offer received'), ('enrolled', 'Enrolled')], db_index=True, max_length=12)),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referrals.referralcode')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_events', to='payments.payment')),
                ('referred_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralPayout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('declined', 'Declined')], db_index=True, default='requested', max_length=12)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='referrals.referralcode')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_snapshot', models.JSONField(default=dict, help_text='The rule as it stood when this reward was earned.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved for payout'), ('paid', 'Paid'), ('void', 'Void (fraud or reversal)')], db_index=True, default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_referral_rewards', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='referrals.referralcode')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='referrals.referralevent')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='referrals.referralpayout')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='referrals.referralrewardrule')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('owner_type', 'student')), fields=('student',), name='uniq_active_code_per_student'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['event_type', 'is_flagged'], name='referrals_r_event_t_cb5fd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralevent',
            constraint=models.UniqueConstraint(fields=('code', 'referred_student', 'event_type'), name='uniq_referral_event'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['status', '-created_at'], name='referrals_r_status_940a00_idx'),
        ),
    ]
