# Generated by Django 5.2.6 on 2026-09-10 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visa_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RequirementCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon key for the frontend.', max_length=50)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'requirement categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_reason', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('language_school', 'Language school'), ('pathway', 'Pathway / foundation provider'), ('other', 'Other')], default='university', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('description', models.TextField(blank=True)),
                ('is_partner', models.BooleanField(default=False, help_text='We hold a formal recruitment agreement with this school.')),
                ('commission_notes', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='schools.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_reason', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('level', models.CharField(choices=[('foundation', 'Foundation / pathway'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('doctorate', 'Doctorate'), ('language', 'Language course')], default='undergraduate', max_length=20)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tuition_currency', models.CharField(blank=True, default='EUR', max_length=3)),
                ('language_of_instruction', models.CharField(blank=True, default='English', max_length=60)),
                ('intakes', models.JSONField(blank=True, default=list, help_text='e.g. ["October 2027", "April 2028"]')),
                ('application_opens', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='schools.school')),
            ],
            options={
                'ordering': ('school__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SchoolRequirementSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('is_template', models.BooleanField(db_index=True, default=False, help_text="A reusable starting point not tied to one school — e.g. 'UK undergraduate standard set'. Most UK universities want near-identical documents, so the admin clones a template instead of rebuilding from scratch (§4.1).")),
                ('notes', models.TextField(blank=True)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='schools.schoolrequirementset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirement_sets', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_sets', to='schools.programme')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_sets', to='schools.school')),
            ],
            options={
                'ordering': ('school__name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('help_text', models.CharField(blank=True, help_text="Shown under the upload box — e.g. 'Certified copy, English translation'.", max_length=300)),
                ('is_required', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('evidence_type', models.CharField(choices=[('document', 'Document upload'), ('form', 'Form response'), ('document_and_form', 'Document + form response'), ('task', 'Task (no upload)'), ('external', 'Handled outside the platform')], default='document', max_length=20)),
                ('accepted_file_types', models.JSONField(blank=True, default=list, help_text='e.g. [".pdf", ".jpg"]')),
                ('max_file_size_mb', models.PositiveIntegerField(default=20)),
                ('allow_multiple_files', models.BooleanField(default=False)),
                ('data_spec', models.JSONField(blank=True, default=dict, help_text='Inline field spec for simple structured data, when a full form is overkill.')),
                ('is_shareable', models.BooleanField(default=False, help_text='The same artefact satisfies this item across every application — a passport is uploaded once and reused (plan §8.4).')),
                ('shareable_key', models.SlugField(blank=True, help_text="Items sharing this key across schools reuse one document, e.g. 'passport'.", max_length=100)),
                ('expires_after_months', models.PositiveIntegerField(blank=True, help_text='Validity window — IELTS is 24 months, police clearances often 6.', null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('due_offset_days', models.IntegerField(blank=True, help_text='Days relative to the application deadline; negative means before it.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_items', to='schools.requirementcategory')),
                ('linked_form', models.ForeignKey(blank=True, help_text='Mini-form for items needing structured data alongside the file (e.g. IELTS score).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirement_items', to='forms_engine.formdefinition')),
                ('requirement_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schools.schoolrequirementset')),
            ],
            options={
                'ordering': ('category__display_order', 'display_order', 'label'),
            },
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active', 'country'], name='schools_sch_is_acti_160ef0_idx'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='uniq_programme_per_school'),
        ),
        migrations.AddIndex(
            model_name='schoolrequirementset',
            index=models.Index(fields=['school', 'status'], name='schools_sch_school__6b0db1_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequirementset',
            index=models.Index(fields=['is_template', 'status'], name='schools_sch_is_temp_157120_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementitem',
            index=models.Index(fields=['requirement_set', 'is_active'], name='schools_req_require_4c122f_idx'),
        ),
    ]
