# Generated by Django 5.2.6 on 2026-09-11 10:10

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.storage.school_logo_path),
        ),
    ]
