# Generated by Django 5.2.6 on 2026-09-11 00:16

import apps.core.encryption
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Offer this channel to users.')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=64)),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=64)),
                ('telegram_bot_username', models.CharField(blank=True, help_text='Without the @.', max_length=64)),
                ('access_token', apps.core.encryption.EncryptedTextField(blank=True)),
                ('webhook_verify_token', apps.core.encryption.EncryptedTextField(blank=True, help_text='Echoed back during provider webhook verification.')),
            ],
            options={
                'verbose_name': 'channel configuration',
                'verbose_name_plural': 'channel configurations',
                'ordering': ('channel',),
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='in_app', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='email', max_length=10),
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('account', 'Account'), ('payment', 'Payment'), ('document', 'Document'), ('application', 'Application'), ('referral', 'Referral'), ('message', 'Message'), ('system', 'System')], max_length=15)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'category'], name='notificatio_user_id_e0a7cc_idx')],
                'unique_together': {('user', 'category', 'channel')},
            },
        ),
    ]
