# Generated by Django 5.2.6 on 2026-09-11 10:10

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_channelconfig_alter_notification_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.storage.message_attachment_path),
        ),
    ]
