# Generated by Django 5.2.6 on 2026-09-10 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(blank=True, help_text='Denormalised actor identity, kept readable after the user is deleted.', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('archive', 'Archived'), ('login', 'Logged in'), ('login_failed', 'Login failed'), ('publish', 'Published'), ('document_verify', 'Document verified'), ('document_reject', 'Document rejected'), ('document_download', 'Document downloaded'), ('payment_status_change', 'Payment status changed'), ('payment_refund', 'Payment refunded'), ('gateway_config_change', 'Gateway config changed'), ('referral_payout', 'Referral payout'), ('checklist_resync', 'Checklist re-synced'), ('permission_change', 'Permission changed'), ('data_export', 'Data exported'), ('data_erasure', 'Data erased')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="{'field': {'from': x, 'to': y}} — never store raw secrets or document contents.")),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system/automated actions (e.g. webhook processing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='core_auditl_target__29612b_idx'), models.Index(fields=['actor', '-created_at'], name='core_auditl_actor_i_502baf_idx')],
            },
        ),
    ]
