# Generated by Django 5.2.6 on 2026-09-10 00:27

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_reason', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='Nigerian', max_length=100)),
                ('country_of_residence', models.CharField(blank=True, default='Nigeria', max_length=100)),
                ('state_of_residence', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +2348012345678.', regex='^\\+?[0-9\\s\\-()]{7,20}$')])),
                ('stage', models.CharField(choices=[('registered', 'Registered'), ('paid', 'Access fee paid'), ('profile_complete', 'Profile complete'), ('applying', 'Applying'), ('offer_received', 'Offer received'), ('visa_stage', 'Visa stage'), ('enrolled', 'Enrolled'), ('dormant', 'Dormant'), ('withdrawn', 'Withdrawn')], db_index=True, default='registered', max_length=20)),
                ('has_platform_access', models.BooleanField(db_index=True, default=False)),
                ('access_granted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('organic', 'Organic'), ('referral', 'Referral'), ('social', 'Social media'), ('event', 'Event / seminar'), ('partner', 'Partner'), ('other', 'Other')], default='organic', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only. Never exposed on the student API.')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +2348012345678.', regex='^\\+?[0-9\\s\\-()]{7,20}$')])),
                ('role', models.CharField(choices=[('student', 'Student'), ('counsellor', 'Counsellor'), ('reviewer', 'Document reviewer'), ('finance', 'Finance'), ('admin', 'Admin'), ('superadmin', 'Super admin')], db_index=True, default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can log into the Django admin backoffice.')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_terms_version', models.CharField(blank=True, max_length=20)),
                ('accepted_privacy_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_privacy_version', models.CharField(blank=True, max_length=20)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('can_manage_students', models.BooleanField(default=False)),
                ('can_review_documents', models.BooleanField(default=False)),
                ('can_manage_schools', models.BooleanField(default=False)),
                ('can_build_forms', models.BooleanField(default=False)),
                ('can_view_payments', models.BooleanField(default=False)),
                ('can_manage_payment_config', models.BooleanField(default=False, help_text='Access to gateway API keys. Grant sparingly.')),
                ('can_issue_refunds', models.BooleanField(default=False)),
                ('can_manage_referrals', models.BooleanField(default=False)),
                ('can_approve_payouts', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_team', models.BooleanField(default=False)),
                ('can_view_audit_log', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__email',),
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify email'), ('reset_password', 'Reset password')], max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
