# Generated by Django 5.2.6 on 2026-09-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_quiet_hours_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='can_publish_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_write_content',
            field=models.BooleanField(default=False),
        ),
    ]
