# Generated by Django 5.2.6 on 2026-09-10 00:27

import apps.applications.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_reason', models.CharField(blank=True, max_length=255)),
                ('intake', models.CharField(blank=True, help_text='e.g. "October 2027"', max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preparing', 'Preparing documents'), ('ready_to_submit', 'Ready to submit'), ('submitted', 'Submitted to school'), ('additional_info', 'School requested more information'), ('offer', 'Offer received'), ('conditional_offer', 'Conditional offer'), ('rejected', 'Rejected by school'), ('accepted_offer', 'Offer accepted by student'), ('visa_applied', 'Visa applied'), ('visa_granted', 'Visa granted'), ('visa_refused', 'Visa refused'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn by student')], db_index=True, default='draft', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('target_submission_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, help_text='School or uni-assist application number.', max_length=100)),
                ('counsellor_notes', models.TextField(blank=True, help_text='Staff-only.')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_version', models.PositiveIntegerField(default=0, help_text='Kept even if the requirement set is later deleted.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_resynced_at', models.DateTimeField(blank=True, null=True)),
                ('progress_basis', models.CharField(choices=[('verified', 'Verified documents only'), ('uploaded', 'Anything uploaded')], default='verified', max_length=10)),
                ('percent_complete', models.PositiveIntegerField(default=0)),
                ('percent_uploaded', models.PositiveIntegerField(default=0)),
                ('required_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('uploaded_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(max_length=100)),
                ('category_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('evidence_type', models.CharField(default='document', max_length=20)),
                ('accepted_file_types', models.JSONField(blank=True, default=list)),
                ('max_file_size_mb', models.PositiveIntegerField(default=20)),
                ('allow_multiple_files', models.BooleanField(default=False)),
                ('shareable_key', models.SlugField(blank=True, max_length=100)),
                ('expires_after_months', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('uploaded', 'Uploaded'), ('pending_review', 'In review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('waived', 'Waived by agency'), ('not_applicable', 'Not applicable')], db_index=True, default='not_started', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, help_text="Inline structured answers (e.g. {'ielts_overall': 6.5}).")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text="Required when rejecting (§10) — 'rejected' with no explanation just creates a support ticket.")),
                ('student_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category_order', 'display_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(max_length=500, upload_to=apps.applications.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, help_text='Detects a student re-uploading the identical file after a rejection.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('superseded', 'Superseded by a newer version')], db_index=True, default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewer_note', models.TextField(blank=True, help_text='Internal note, not shown to the student.')),
                ('virus_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('virus_scan_result', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_reason', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('shareable_key', models.SlugField(blank=True, help_text='Matches RequirementItem.shareable_key so the same file satisfies many checklists.', max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, help_text='Passport expiry, IELTS validity — drives renewal reminders.', null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
