# Generated by Django 5.2.6 on 2026-09-10 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('applications', '0001_initial'),
        ('forms_engine', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='schools.programme'),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='schools.school'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='applications.application'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='source_requirement_set',
            field=models.ForeignKey(blank=True, help_text='The exact version this checklist was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_instances', to='schools.schoolrequirementset'),
        ),
        migrations.AddField(
            model_name='checklistiteminstance',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applications.checklistinstance'),
        ),
        migrations.AddField(
            model_name='checklistiteminstance',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='forms_engine.formsubmission'),
        ),
        migrations.AddField(
            model_name='checklistiteminstance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistiteminstance',
            name='source_requirement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='schools.requirementitem'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_documents', to='schools.requirementcategory'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='current_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='applications.documentupload'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='applications.studentdocument'),
        ),
        migrations.AddField(
            model_name='checklistiteminstance',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='applications.studentdocument'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-created_at'], name='application_status_db7a61_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', 'status'], name='application_student_7f76d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'school', 'programme', 'intake'), name='uniq_application_per_intake'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['student', 'shareable_key'], name='application_student_d16035_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['status', '-created_at'], name='application_status_15357f_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentupload',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_upload_version'),
        ),
        migrations.AddIndex(
            model_name='checklistiteminstance',
            index=models.Index(fields=['checklist', 'status'], name='application_checkli_a9c6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistiteminstance',
            index=models.Index(fields=['status', '-updated_at'], name='application_status_50f3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistiteminstance',
            index=models.Index(fields=['shareable_key'], name='application_shareab_86d80d_idx'),
        ),
    ]
