# Generated by Django 5.2.6 on 2026-09-10 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('audience', models.CharField(choices=[('public', 'Public (no login required)'), ('prospect', 'Any logged-in student'), ('paid_student', 'Students with platform access'), ('admin_only', 'Agency staff only')], default='prospect', max_length=20)),
                ('purpose', models.CharField(choices=[('student_intake', 'Student intake / profile'), ('school_requirements', 'School & requirement upload'), ('application_supplement', 'Per-application supplement'), ('requirement_item', 'Attached to a checklist item'), ('consultation_log', 'Internal consultation log'), ('general', 'General / standalone')], default='general', max_length=30)),
                ('schema', models.JSONField(default=dict, help_text='Sections and fields — see apps.forms_engine.schema.')),
                ('allow_multiple_submissions', models.BooleanField(default=False, help_text='If false, one submission per subject per form slug.')),
                ('allow_drafts', models.BooleanField(default=True, help_text='Students can save a partial answer set and return later.')),
                ('submit_button_label', models.CharField(blank=True, default='Submit', max_length=60)),
                ('success_message', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('change_note', models.CharField(blank=True, help_text='What changed in this version, for the audit trail.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('slug', '-version'),
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_slug', models.SlugField(help_text='Denormalised from the definition so submissions group across versions.', max_length=140)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('superseded', 'Superseded by a newer submission')], db_index=True, default='draft', max_length=12)),
                ('data', models.JSONField(default=dict, help_text='Validated answers, keyed by field key.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='applications.application')),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms_engine.formdefinition')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
