# Generated by Django 5.2.6 on 2026-09-10 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('forms_engine', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='formdefinition',
            index=models.Index(fields=['purpose', 'status'], name='forms_engin_purpose_bfccfc_idx'),
        ),
        migrations.AddIndex(
            model_name='formdefinition',
            index=models.Index(fields=['audience', 'status'], name='forms_engin_audienc_b7e452_idx'),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='uniq_form_slug_version'),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('slug',), name='uniq_published_form_per_slug'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form_slug', 'status'], name='forms_engin_form_sl_7b4d66_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['student', 'form_slug'], name='forms_engin_student_a0031f_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['school', 'form_slug'], name='forms_engin_school__f8fd4e_idx'),
        ),
    ]
