# Generated by Django 5.2.6 on 2026-09-10 00:27

import apps.core.encryption
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual / bank transfer')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('transactions_checked', models.PositiveIntegerField(default=0)),
                ('mismatches_found', models.PositiveIntegerField(default=0)),
                ('payments_corrected', models.PositiveIntegerField(default=0)),
                ('unknown_transactions', models.PositiveIntegerField(default=0, help_text='Successful at the gateway with no Payment row here — investigate.')),
                ('details', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual / bank transfer')], db_index=True, max_length=20)),
                ('label', models.CharField(blank=True, help_text='Shown to students at checkout.', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('public_key', models.CharField(blank=True, max_length=255)),
                ('secret_key', apps.core.encryption.EncryptedTextField(blank=True)),
                ('encryption_key', apps.core.encryption.EncryptedTextField(blank=True, help_text="Flutterwave's separate encryption key, where required.")),
                ('webhook_secret', apps.core.encryption.EncryptedTextField(blank=True, help_text="Paystack: the secret key. Flutterwave: the 'secret hash'.")),
                ('secret_key_fingerprint', models.CharField(blank=True, help_text='Non-reversible identifier so staff can confirm which key is live.', max_length=12)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gateway_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_order', 'gateway'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Our reference, sent to the gateway.', max_length=64, unique=True)),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual / bank transfer')], max_length=20)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('email', models.EmailField(help_text='Kept even if the student record is later removed.', max_length=254)),
                ('purpose', models.CharField(choices=[('access_fee', 'Platform access fee'), ('application_fee', 'Application fee'), ('service_fee', 'Service fee'), ('tuition_deposit', 'Tuition deposit'), ('other', 'Other')], default='access_fee', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('amount_settled', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gateway_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], db_index=True, default='pending', max_length=20)),
                ('status_reason', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, help_text='card, bank_transfer, ussd …', max_length=40)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('confirmed_by_webhook', models.BooleanField(default=False, help_text='True only when a signature-verified webhook confirmed this payment.')),
                ('confirmed_by_reconciliation', models.BooleanField(default=False, help_text='Set when the nightly job found a success the webhook never delivered.')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciliation_note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='applications.application')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.studentprofile')),
                ('gateway_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentgatewayconfig')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('reason', models.TextField(help_text='Required — refunds are answerable to the refund policy (§10).')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('declined', 'Declined')], db_index=True, default='requested', max_length=12)),
                ('gateway_reference', models.CharField(blank=True, max_length=128)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual / bank transfer')], db_index=True, max_length=20)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Signature verified'), ('invalid_signature', 'Invalid signature'), ('processed', 'Processed'), ('duplicate', 'Duplicate — ignored'), ('failed', 'Processing failed'), ('ignored', 'Event type not handled')], db_index=True, default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayconfig',
            constraint=models.UniqueConstraint(fields=('gateway', 'currency', 'is_test_mode'), name='uniq_gateway_currency_mode'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'purpose', 'status'], name='payments_pa_student_44e371_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_fb31b8_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['gateway', 'status', '-created_at'], name='payments_we_gateway_f9cc08_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', '-created_at'], name='payments_we_event_t_8f0131_idx'),
        ),
    ]
