# Generated by Django 5.2.6 on 2026-09-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual / bank transfer'), ('mock', 'Mock (no money moves)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual / bank transfer'), ('mock', 'Mock (no money moves)')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual / bank transfer'), ('mock', 'Mock (no money moves)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual / bank transfer'), ('mock', 'Mock (no money moves)')], db_index=True, max_length=20),
        ),
    ]
