# Generated by Django 5.2.6 on 2026-09-13 11:18

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_gateway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g. "Proof of funds".', max_length=120)),
                ('amount_display', models.CharField(blank=True, help_text='The figure or range, as you would say it. Leave blank and the row shows “ask us” — which is the right answer when nobody has checked.', max_length=120)),
                ('note', models.CharField(help_text='Why it exists, or who it is paid to. One line.', max_length=240)),
                ('verified_on', models.DateField(blank=True, help_text='The day somebody last checked this against a real source. Past the staleness window it stops showing the figure automatically.', null=True)),
                ('verified_source', models.CharField(blank=True, help_text='Where the figure came from. Internal — never shown to a student.', max_length=240)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('access_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='What platform access costs, once. This is the number the gateway charges and the number every page shows — they cannot disagree.', max_digits=12)),
                ('access_fee_currency', models.CharField(default='NGN', help_text='ISO 4217, e.g. NGN.', max_length=3)),
                ('access_fee_note', models.CharField(blank=True, default='Covers everything from the first shortlist to landing on campus.', help_text='One line, shown next to the price.', max_length=200)),
                ('estimate_stale_after_days', models.PositiveSmallIntegerField(default=120, help_text='A cost estimate not verified inside this many days stops showing its figure and shows “ask us” instead. A stale number is worse than none.')),
            ],
            options={
                'verbose_name': 'pricing',
                'verbose_name_plural': 'pricing',
            },
        ),
    ]
